# -*- coding: utf-8 -*-
"""model_training_May08.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1Kl3dIKM5p5AHMm252n4SGSat38g6Vbgc
"""

# Apr 25, 2020
# increse data by adding videos from youtube

import numpy as np
import json
import os
import csv
import pandas as pd

# read json 2-d pose as data, without using: 
#     {15, "REye"},
#     {16, "LEye"},
#     {17, "REar"},
#     {18, "LEar"}


path = r'C:\Users\sam\Desktop\data_mobilenet_thin\json\fall'


def input_data(basepath):
  data = []
  entries = os.listdir(basepath)
  index = 1
  for entry in entries:
    path = os.path.join(basepath, entry)
    frames = os.listdir(path)
    for frame in frames:
      frame_path = os.path.join(path, frame)
      with open(frame_path, mode='r') as json_file:
        people_dict = json.load(json_file)
        people = people_dict["people"]
        pose_keypoints_2d = []
        # fill missing data as 0
        if len(people) == 0:
          pose_keypoints_2d = [0] * 54
        else:
          full_pose = people[0].get("pose_keypoints_2d")
          pose_keypoints_2d = full_pose[:54]
          
        #print(frame)
        pose_keypoints_2d.append("fall_%03d"%index +"_" + frame.split('.')[0])
        # each pose_keypoints_2d: 
        #    [431.949, 196.241, 0.0564434, 437.194, 187.749, 0.552267,...'fall-06-cam0_000000000065_keypoints']
        # OR [123.949, 283.241, 0.0564434, 437.194, 187.749, 0.552267,...'43_000000000000_keypoints']
        data.append(pose_keypoints_2d)
    index+=1
  return data



data = input_data(path)
print("finish data. the length of dataset: ", len(data)) 

data_csv = pd.DataFrame.from_records(data)
data_csv.to_csv(r'C:\Users\sam\Desktop\fall.csv', index = False, header=False)


